# pytest.ini
[pytest]
python_files = *_tests.py test_*.py  # Это мы добавили в предыдущем шаге
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*    # Устанавливает правила для тестовых файлов

markers =
    ui: Запускает все UI автотесты
    smoke: Запускает smoke UI автотесты
    regression: Запускает regression UI автотесты
    slow: Маркировка для медленных тестов
    registration: Запускает UI тесты на регистрацию
    authorization: Запускате UI тесты на авторизацию